openapi: 3.0.3
info:
  contact:
    email: api.inquiry@expert.ai
    name: expert.ai
    url: 'https://expert.ai/'
  description: The `emotional-traits` document classification resources of the expert.ai Natural Language API classify documents in terms of feelings like joy, surprise, irritation, etc. expressed in the text. In addition, when requested with a specific query-string parameter, they return extra-data containing the [main groups](https://docs.expert.ai/nlapi/latest/reference/emotional-traits-main-groups/) to which the emotional traits belong. Especially with longer texts, main groups are an useful abstract of the detailed classification.<br />The Natural Language API has a [general OpenAPI contract](https://github.com/therealexpertai/nlapi-openapi-specification/blob/master/nlapi.yaml) specifying how to use document classification resources. This specific sub-contract specifies how to use the `emotional-traits` taxonomy resources in a special way to also obtain the main groups as additional output.
  title: expert.ai Natural Language API - Emotional traits classification with main groups
  version: v2
externalDocs:
  description: API documentation
  url: 'https://docs.expert.ai/nlapi/v2/'
servers:
  - url: 'https://nlapi.expert.ai/v2'
tags:
  - description: Emotional traits classification API endpoints
    name: Emotional traits classification
paths:
  /categorize/emotional-traits/{language}:
    post:
      description: Classification of the posted text
      parameters:
       - description: Two letter ISO code of the input document language. Currently the `emotional-traits` taxonomy is available for the English language (language code `en`), support for more languages will be added in future releases.
         in: path
         name: language
         required: true
         schema:
           type: string
           enum:
             - en
             - de
       - description: Classification features, specify `extradata` to obtain main groups
         in: query
         name: features
         required: true
         schema:
           type: string
           enum:
             - extradata      
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'nlapi.yaml#/components/schemas/AnalysisRequest'
        description: The document to be classified
      responses:
        '200':
          $ref: "#/components/responses/200EmotionalTraitsCategorize"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '413':
          description: Request Entity Too Large
        '500':
          description: Internal Server Error
      security:
        - bearerAuth: []
      summary: Emotional traits classification with extra data containing the main groups of emotions
      tags:
        - Document classification
components:
  responses:
    200EmotionalTraitsCategorize:
      description: Resource response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmotionalTraitsResponse'
  schemas:
    EmotionalTraitsResponse:
      description: Classification resource response
      properties:
        success:
          description: Operation completed successfully (true/false)
          type: boolean
        errors:
          description: Service errors
          type: array
          items:
            $ref: 'nlapi.yaml#/components/schemas/ServiceError'
        data:
          allOf:
            - $ref: 'nlapi.yaml#/components/schemas/CategorizeDocument'
            - $ref: '#/components/schemas/EmotionalTraitsDocument'
    Group:
      description: Group of emotional traits
      properties:
        id:
          description: ID of the category corresponding to the group inside the taxonomy
          type: string
        label:
          description: Label of the category corresponding to the group inside the taxonomy
          type: string
        position:
          description: Group rank
          format: int32
          type: integer
    EmotionalTraitsDocument:
      description: Categorization data
      properties:
        extraData:
          type: object
          description: Extra-data containing main groups
          properties:
            groups:
              description: Main groups
              type: array
              items:
                $ref: '#/components/schemas/Group'
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http