openapi: 3.0.3
info:
  title: "expert.ai PII detector"
  version: "v2"
  description: "PII detector is the Natural Language API extension that detects personally identifiable information"
  contact:
    email: api.inquiry@expert.ai
    name: expert.ai
    url: 'https://expert.ai/'
externalDocs:
  description: API documentation
  url: 'https://docs.expert.ai/nlapi/v2/'
servers:
  - url: "https://nlapi.expert.ai/v2"
tags:
  - name: PII detection
paths:
  "/detect/pii/{language}":
    post:
      tags:
        - PII detection
      parameters:
        - name: "language"
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'nlapi.yaml#/components/schemas/AnalysisRequest'        
      responses:
        "200":
          $ref: "#/components/responses/200PIIDetection"
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "413":
          description: "Request Entity Too Large"
        "500":
          description: "Internal Server Error"
      security:
        - bearerAuth: []  
components:
  securitySchemes:
      "bearerAuth":
        bearerFormat: JWT
        scheme: bearer
        type: http
  responses:
    200PIIDetection:
      description: "OK"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PIIResponse"
  schemas:
    PIIBaseItem:
      description: "Type with properties inherited by all JSON-LD graph PII types"
      properties:
        "@type":
          description: "JSON-LD graph item type"
          type: string
        "@id":
          description: "JSON-LD graph item id"
          type: string
        "matches":
          description: "Text matches of items' properties"
          type: array
          items:
            properties:
              "start":
                description: "Property value in the text, zero-based position of the first character"
                format: int64
                type: integer
              "end":
                description: "Property value in the text, zero-based position of the character after the last"
                format: int64
                type: integer
              "value":
                description: "Property value"
                type: string
              "name":
                description: "Property name"
                type: string
    PIIPerson:
      description: "Person"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "givenName":
              type: string
            "familyName":
              type: string
            "age":
              type: string
            "gender":
              type: string
            "nationality":
              type: string
            "birthDate":
              type: string
            "birthPlace":
              type: string
            "deathDate":
              type: string
            "deathPlace":
              type: string
            "dateTime":
              type: array
              items:
                type: string
            "person":
              type: string
    PIIPostalAddress:
      description: "Postal address"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "address":
              type: string
            "streetAddress":
              type: string
            "addressCountry":
              type: string
            "addressLocality":
              type: string
            "addressRegion":
              type: string
            "postOfficeBoxNumber":
              type: string
            "postalCode":
              type: string
    PIIBankAccount:
      description: "Bank account"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "IBAN":
              type: string
            "IBANcountry":
              type: string
    PIIFinancialProduct:
      description: "Credit card"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "creditDebitNumber":
              type: string
            "CVV":
              type: string
            "expirationDate":
              type: string
    PIItelephone:
      description: "Phone number"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "telephone":
              type: string
    PIIemail:
      description: "E-mail address"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "email":
              type: string
    PIIURL:
      description: "URL"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "URL":
              type: string
    PIIIP:
      description: "Internet Protocol (IP) address"
      allOf:
        - $ref: "#/components/schemas/PIIBaseItem"
        - properties:
            "IP":
              type: string
    PIIItem:
      description: "Personally Identifiable Information (PII) item"
      oneOf:
        - $ref: "#/components/schemas/PIIPerson"
        - $ref: "#/components/schemas/PIIPostalAddress"
        - $ref: "#/components/schemas/PIIBankAccount"
        - $ref: "#/components/schemas/PIIFinancialProduct"
        - $ref: "#/components/schemas/PIItelephone"
        - $ref: "#/components/schemas/PIIemail"
        - $ref: "#/components/schemas/PIIURL"
        - $ref: "#/components/schemas/PIIIP"
    PIIJSONLD:
      description: "JSON-LD format output"
      properties:
        "@context":
          type: object
          description: "JSON-LD context"
          properties:
            "@version":
              type: string
            "schema":
              type: string
            "matches":
              type: string
            "start":
              type: object
              properties:
                "@id":
                  type: string
            "end":
              type: object
              properties:
                "@id":
                  type: string
            "text":
              type: string
            "additionalProperty":
              type: string
            "URL":
              type: string
            "IP":
              type: string
            "type":
              type: string
            "email":
              type: string
            "IBAN":
              type: string
            "IBANcountry":
              type: string
            "postalAddress":
              type: string
            "creditDebitNumber":
              type: string
            "CVV":
              type: string
            "expirationDate":
              type: string
            "birthDate":
              type: string
            "deathDate":
              type: string
            "dateTime":
              type: string
            "telephone":
              type: string
            "address":
              type: string
            "streetAddress":
              type: string
            "addressCountry":
              type: string
            "postalCode":
              type: string
            "addressLocality":
              type: string
            "addressRegion":
              type: string
            "person":
              type: string
            "age":
              type: string
            "familyName":
              type: string
            "gender":
              type: string
            "givenName":
              type: string
            "nationality":
              type: string
            "birthPlace":
              type: string
            "deathPlace":
              type: string
            "postOfficeBoxNumber":
              type: string
        "@graph":
          description: "JSON-LD graph data"
          type: array
          items:
            $ref: "#/components/schemas/PIIItem"
    PIIExtraData: 
      description: "PII Extra Data"
      properties:
        "JSON-LD":
          $ref: "#/components/schemas/PIIJSONLD"
    PIIDocument:
      description: "PII Specific Document properties"
      properties:
        "extraData":
          $ref: "#/components/schemas/PIIExtraData"
    PIIResponse:
      description: "Detector's response"
      properties:
        "success":
          description: "Success flag"
          type: boolean
        "error":
          description: "Error description"
          properties:
            "code":
              description: "Error code"
              type: string
            "message":
              description: "Error message"
              type: string
        "data":
          allOf:
            - $ref: "nlapi.yaml#/components/schemas/DetectorBaseDocument"
            - $ref: "#/components/schemas/PIIDocument"
                