openapi: 3.0.3
info:
  title: "expert.ai Writeprint detector"
  version: "v2"
  description: "Writeprint detector is the Natural Language API extension that detects 60 style markers to help determine the author's 'writeprint' with 60 stylometric indexes"
  contact:
    email: api.inquiry@expert.ai
    name: expert.ai
    url: 'https://expert.ai/'
externalDocs:
  description: API documentation
  url: 'https://docs.expert.ai/nlapi/v2/'
servers:
  - url: "https://nlapi.expert.ai/v2"
tags:
  - name: Writeprint detection
paths:
  "/detect/writeprint/{language}":
    post:
      tags:
        - Writeprint detection
      parameters:
        - name: "language"
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'nlapi.yaml#/components/schemas/AnalysisRequest'            
      responses:
        "200":
          $ref: "#/components/responses/200WriteprintDetection"
        "400":
          description: Bad Request
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        "413":
          description: "Request Entity Too Large"
        "500":
          description: "Internal Server Error"
      security:
        - bearerAuth: []          
components:
  securitySchemes:
    "bearerAuth":
      bearerFormat: JWT
      scheme: bearer
      type: http
  responses:
    200WriteprintDetection:
      description: "OK"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/WriteprintResponse"
  schemas:
    ReadabilityIndex:
      description: "A readability index"
      properties:
        "@type":
          type: string
        "name":
          description: "Index name"
          type: string
        "value":
          description: "Index value"
          type: number
        "readabilityLevel":
          description: "Degree of difficulty"
          type: string
    CounterIndex:
      description: "A counter index"
      properties:
        "total":
          type: number
    PerSentenceIndex:
      description: "A 'per sentence' index"
      properties:
        "mean":
          type: number
        "standardDeviation":
          type: number
        "meanAbsoluteDeviation":
          type: number
    WriteptintGraphStructuredIntexes:
      properties:
        "sentences":
          $ref: "#/components/schemas/CounterIndex"
        "tokens":
          $ref: "#/components/schemas/CounterIndex"
        "tokenLengthPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "verbTypes":
          $ref: "#/components/schemas/CounterIndex"
        "charactersPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "atomsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "tokensPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "phrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "verbTypesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "smallFirstLetterSentences":
          $ref: "#/components/schemas/PerSentenceIndex"
        "capitalFirstLetterSentences":
          $ref: "#/components/schemas/PerSentenceIndex"
        "adjectivesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "adverbsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "articlesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "auxiliariesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "conjunctionsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "nounsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "properNounsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "punctuationPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "prepositionsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "pronounsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "particlesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "verbsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "namedEntitiesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "adjectivePhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "conjunctionPhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "adverbPhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "nounPhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "nominalPredicatesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "prepositionPhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "relativePhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "verbPhrasesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "emoticonsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "dotsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "multipleDotsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "questionMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "multipleQuestionMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "exclamationMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "multipleExclamationMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "exclamationMarkQuestionMarkSequencesPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "commasPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "colonsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "semicolonsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "singleQuotationMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "doubleQuotationMarksPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "unknownConceptsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "functionWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "commonlyMisspelledWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "mostCommonWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "academicLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "businessLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "crimeLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "laymanLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "legalLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "militaryLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "politicalLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
        "socialMediaLanguageWordsPerSentence":
          $ref: "#/components/schemas/PerSentenceIndex"
    WriteprintJSONLD: 
      description: "JSON-LD format output"
      properties:
        "@context":
          description: "JSON-LD context"
        "@graph":
          description: "JSON-LD graph data"
          type: array
          items:
            type: object
            properties:
              "@type":
                type: string
              "readabilityIndexes":
                type: array
                items:
                  $ref: "#/components/schemas/ReadabilityIndex"
              "structureIndexes":
                $ref: "#/components/schemas/WriteptintGraphStructuredIntexes"
    WriteprintExtraData:
      description: "Writeprint Extra Data"
      properties:
        "JSON-LD":
          $ref: "#/components/schemas/WriteprintJSONLD"
    WriteprintDocument:
      description: "Writeprint Specific Document properties"
      properties:
        extraData:
          $ref: "#/components/schemas/WriteprintExtraData"
    WriteprintResponse:
      description: "Detector's response"
      properties:
        "success":
          description: "Success flag"
          type: boolean
        "error":
          description: "Error description"
          properties:
            "code":
              description: "Error code"
              type: string
            "message":
              description: "Error message"
              type: string
        "data":
          allOf:
            - $ref: "nlapi.yaml#/components/schemas/DetectorBaseDocument"
            - $ref: "#/components/schemas/WriteprintDocument"            
